SELECT 
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '0' then 1 end) as "0 Books Main 0",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '2' then 1 end) as "2 Adult Music Main 1",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '3' then 1 end) as "3 Juv Music Main 2",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '6' then 1 end) as "6 REF Main 3",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '7' then 1 end) as "7 Lending Art Main 4",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '8' then 1 end) as "8 ILL Main 5",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '9' then 1 end) as "9 Periodicals Main 6",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '10' then 1 end) as "Perrot Tote Bag Books Main 7",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '16' then 1 end) as "JUV Spknwrd Cass. Main 8",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '17' then 1 end) as "JUV music cass. Books Main 9",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '18' then 1 end) as "Park/Museum Pass Main 10",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '20' then 1 end) as "Juvenile Books Main 11",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '22' then 1 end) as "Adult Spknwrd CDs Main 12",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '23' then 1 end) as "Juv Spnwrd CDs Main 13",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '31' then 1 end) as "Perr-A Express Books Main 14",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '37' then 1 end) as "Perr-J Periodicals Main 15",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '38' then 1 end) as "Perr-A Playaways Main 16",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '39' then 1 end) as "Perr-J Playaways Main 17",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '40' then 1 end) as "E Readers Main 18",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '41' then 1 end) as "Adult Non-Fic DVDs Main 19",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '42' then 1 end) as "DVD Children Main 20",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '44' then 1 end) as "DVD Adult Main 21",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '46' then 1 end) as "Perr-A Express DVDs Main 22",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '50' then 1 end) as "Ebooks Main 23",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '60' then 1 end) as "J Books with CD Main 24",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '61' then 1 end) as "Juv Multimedia Kit Main 25",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '62' then 1 end) as "Adult Game Main 26",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '63' then 1 end) as "Juv Game Main 27",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'o' and circ.itype_code_num = '80' then 1 end) as "Audbk Download Main 28",

count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '0' then 1 end) as "0 Books Main 29",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '2' then 1 end) as "2 Adult Music Main 30",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '3' then 1 end) as "3 Juv Music Main 31",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '6' then 1 end) as "6 REF Main 32",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '7' then 1 end) as "7 Lending Art Main 33",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '8' then 1 end) as "8 ILL Main 34",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '9' then 1 end) as "9 Periodicals Main 35",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '10' then 1 end) as "Perrot Tote Bag Books Main 36",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '16' then 1 end) as "JUV Spknwrd Cass. Main 37",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '17' then 1 end) as "JUV music cass. Books Main 38",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '18' then 1 end) as "Park/Museum Pass Main 39",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '20' then 1 end) as "Juvenile Books Main 40",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '22' then 1 end) as "Adult Spknwrd CDs Main 41",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '23' then 1 end) as "Juv Spnwrd CDs Main 42",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '31' then 1 end) as "Perr-A Express Books Main 43",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '37' then 1 end) as "Perr-J Periodicals Main 44",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '38' then 1 end) as "Perr-A Playaways Main 45",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '39' then 1 end) as "Perr-J Playaways Main 46",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '40' then 1 end) as "E Readers Main 47",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '41' then 1 end) as "Adult Non-Fic DVDs Main 48",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '42' then 1 end) as "DVD Children Main 49",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '44' then 1 end) as "DVD Adult Main 50",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '46' then 1 end) as "Perr-A Express DVDs Main 51",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '50' then 1 end) as "Ebooks Main 52",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '60' then 1 end) as "J Books with CD Main 53",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '61' then 1 end) as "Juv Multimedia Kit Main 54",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '62' then 1 end) as "Adult Game Main 55",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '63' then 1 end) as "Juv Game Main 56",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'r' and circ.itype_code_num = '80' then 1 end) as "Audbk Download Main 57",

count (case when circ.stat_group_code_num <> '201' and circ.stat_group_code_num <> '210' and circ.stat_group_code_num <> '310' and circ.stat_group_code_num <> '311' and circ.stat_group_code_num <> '750' and circ.stat_group_code_num <> '751'  and circ.op_code = 'i' then 1 end) as " Main checkin 58",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'u' then 1 end) as "Main inhouse 59",
count (case when circ.item_location_code like 'gm%' and circ.op_code = 'f' then 1 end) as "Main Holds 60",
count (case when (circ.stat_group_code_num = '939' or circ.stat_group_code_num = '940' or circ.stat_group_code_num = '942' or circ.stat_group_code_num = '943' or circ.stat_group_code_num = '944') and circ.op_code = 'o' then 1 end) as "Main selfcheck 61",
count (case when circ.op_code = 'o' and circ.pcode3 <> '0' and circ.item_location_code like 'gm%' then 1 end) as "C-Car Check-outs 62",
count (case when circ.op_code = 'o' and (circ.ptype_code = '15' or circ.ptype_code = '22' or circ.ptype_code = '28') and circ.item_location_code like 'gm%' then 1 end) as "EAN Check-outs 63",
count (case when (circ.op_code = 'o' and circ.ptype_code = '12') or (circ.op_code = 'r' and circ.ptype_code = '12') then 1 end) as " ILL Loaned 64",
count (case when (circ.op_code = 'o' and circ.itype_code_num = '8') or (circ.op_code = 'r' and circ.itype_code_num = '8') then 1 end) as " ILL Borrowed 65",

count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '0' then 1 end) as "0 Books BYR 66",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '2' then 1 end) as "2 Adult Music BYR 67",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '3' then 1 end) as "3 Juv Music BYR 68",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '6' then 1 end) as "6 REF BYR 69",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '7' then 1 end) as "7 Lending Art BYR 70",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '8' then 1 end) as "8 ILL BYR 71",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '9' then 1 end) as "9 Periodicals BYR 72",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '10' then 1 end) as "Perrot Tote Bag Books BYR 73",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '16' then 1 end) as "JUV Spknwrd Cass. BYR 74",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '17' then 1 end) as "JUV music cass. Books BYR 75",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '18' then 1 end) as "Park/Museum Pass BYR 76",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '20' then 1 end) as "Juvenile Books BYR 77",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '22' then 1 end) as "Adult Spknwrd CDs BYR 78",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '23' then 1 end) as "Juv Spnwrd CDs BYR 79",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '31' then 1 end) as "Perr-A Express Books BYR 80",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '37' then 1 end) as "Perr-J Periodicals BYR 81",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '38' then 1 end) as "Perr-A Playaways BYR 82",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '39' then 1 end) as "Perr-J Playaways BYR 83",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '40' then 1 end) as "E Readers BYR 84",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '41' then 1 end) as "Adult Non-Fic DVDs BYR 85",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '42' then 1 end) as "DVD Children BYR 86",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '44' then 1 end) as "DVD Adult BYR 87",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '46' then 1 end) as "Perr-A Express DVDs BYR 88",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '50' then 1 end) as "Ebooks BYR 89",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '60' then 1 end) as "J Books with CD BYR 90",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '61' then 1 end) as "Juv Multimedia Kit BYR 91",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '62' then 1 end) as "Adult Game BYR 92",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '63' then 1 end) as "Juv Game BYR 93",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'o' and circ.itype_code_num = '80' then 1 end) as "Audbk Download BYR 94",

count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '0' then 1 end) as "0 Books BYR 95",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '2' then 1 end) as "2 Adult Music BYR 96",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '3' then 1 end) as "3 Juv Music BYR 97",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '6' then 1 end) as "6 REF BYR 98",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '7' then 1 end) as "7 Lending Art BYR 99",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '8' then 1 end) as "8 ILL BYR 100",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '9' then 1 end) as "9 Periodicals BYR 101",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '10' then 1 end) as "Perrot Tote Bag Books BYR 102",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '16' then 1 end) as "JUV Spknwrd Cass. BYR 103",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '17' then 1 end) as "JUV music cass. Books BYR 104",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '18' then 1 end) as "Park/Museum Pass BYR 105",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '20' then 1 end) as "Juvenile Books BYR 106",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '22' then 1 end) as "Adult Spknwrd CDs BYR 107",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '23' then 1 end) as "Juv Spnwrd CDs BYR 108",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '31' then 1 end) as "Perr-A Express Books BYR 109",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '37' then 1 end) as "Perr-J Periodicals BYR 110",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '38' then 1 end) as "Perr-A Playaways BYR 111",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '39' then 1 end) as "Perr-J Playaways BYR 112",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '40' then 1 end) as "E Readers BYR 113",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '41' then 1 end) as "Adult Non-Fic DVDs BYR 114",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '42' then 1 end) as "DVD Children BYR 115",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '44' then 1 end) as "DVD Adult BYR 116",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '46' then 1 end) as "Perr-A Express DVDs BYR 117",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '50' then 1 end) as "Ebooks BYR 118",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '60' then 1 end) as "J Books with CD BYR 119",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '61' then 1 end) as "Juv Multimedia Kit BYR 120",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '62' then 1 end) as "Adult Game BYR 121",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '63' then 1 end) as "Juv Game BYR 122",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'r' and circ.itype_code_num = '80' then 1 end) as "Audbk Download BYR 123",

count (case when circ.op_code = 'i' and circ.stat_group_code_num = '201' then 1 end) as " BYR checkin 124",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'u' then 1 end) as "BYR inhouse 125",
count (case when circ.item_location_code like 'gb%' and circ.op_code = 'f' then 1 end) as "BYR Holds 126",
count (case when circ.stat_group_code_num = '210' and circ.op_code = 'o' then 1 end) as "BYR selfcheck 127",
count (case when circ.op_code = 'o' and circ.pcode3 <> '0' and circ.item_location_code like 'gb%' then 1 end) as "BYR C-Car Check-outs 128",
count (case when circ.op_code = 'o' and (circ.ptype_code = '15' or circ.ptype_code = '22' or circ.ptype_code = '28') and circ.item_location_code like 'gb%' then 1 end) as "BYR EAN Check-outs 129",

count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '0' then 1 end) as "0 Books COS 130",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '2' then 1 end) as "2 Adult Music COS 2",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '3' then 1 end) as "3 Juv Music COS 3",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '6' then 1 end) as "6 REF COS 4",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '7' then 1 end) as "7 Lending Art COS 5",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '8' then 1 end) as "8 ILL COS 6",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '9' then 1 end) as "9 Periodicals COS 7",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '10' then 1 end) as "Perrot Tote Bag Books COS 8",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '16' then 1 end) as "JUV Spknwrd Cass. COS 9",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '17' then 1 end) as "JUV music cass. Books COS 10",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '18' then 1 end) as "Park/Museum Pass COS 11",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '20' then 1 end) as "Juvenile Books COS 12",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '22' then 1 end) as "Adult Spknwrd CDs COS 13",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '23' then 1 end) as "Juv Spnwrd CDs COS 14",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '31' then 1 end) as "Perr-A Express Books COS 15",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '37' then 1 end) as "Perr-J Periodicals COS 16",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '38' then 1 end) as "Perr-A Playaways COS 17",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '39' then 1 end) as "Perr-J Playaways COS 18",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '40' then 1 end) as "E Readers COS 19",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '41' then 1 end) as "Adult Non-Fic DVDs COS 20",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '42' then 1 end) as "DVD Children COS 21",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '44' then 1 end) as "DVD Adult COS 22",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '46' then 1 end) as "Perr-A Express DVDs COS 23",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '50' then 1 end) as "Ebooks COS 24",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '60' then 1 end) as "J Books with CD COS 25",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '61' then 1 end) as "Juv Multimedia Kit COS 26",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '62' then 1 end) as "Adult Game COS 27",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '63' then 1 end) as "Juv Game COS 28",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'o' and circ.itype_code_num = '80' then 1 end) as "Audbk Download COS 29",

count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '0' then 1 end) as "0 Books COS 30",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '2' then 1 end) as "2 Adult Music COS 31",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '3' then 1 end) as "3 Juv Music COS 32",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '6' then 1 end) as "6 REF COS 33",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '7' then 1 end) as "7 Lending Art COS 34",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '8' then 1 end) as "8 ILL COS 35",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '9' then 1 end) as "9 Periodicals COS 36",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '10' then 1 end) as "Perrot Tote Bag Books COS 37",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '16' then 1 end) as "JUV Spknwrd Cass. COS 38",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '17' then 1 end) as "JUV music cass. Books COS 39",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '18' then 1 end) as "Park/Museum Pass COS 40",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '20' then 1 end) as "Juvenile Books COS 41",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '22' then 1 end) as "Adult Spknwrd CDs COS 42",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '23' then 1 end) as "Juv Spnwrd CDs COS 43",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '31' then 1 end) as "Perr-A Express Books COS 44",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '37' then 1 end) as "Perr-J Periodicals COS 45",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '38' then 1 end) as "Perr-A Playaways COS 46",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '39' then 1 end) as "Perr-J Playaways COS 47",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '40' then 1 end) as "E Readers COS 48",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '41' then 1 end) as "Adult Non-Fic DVDs COS 49",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '42' then 1 end) as "DVD Children COS 50",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '44' then 1 end) as "DVD Adult COS 51",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '46' then 1 end) as "Perr-A Express DVDs COS 52",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '50' then 1 end) as "Ebooks COS 53",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '60' then 1 end) as "J Books with CD COS 54",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '61' then 1 end) as "Juv Multimedia Kit COS 55",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '62' then 1 end) as "Adult Game COS 56",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '63' then 1 end) as "Juv Game COS 57",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'r' and circ.itype_code_num = '80' then 1 end) as "Audbk Download COS 58",

count (case when circ.op_code = 'i' and circ.stat_group_code_num = '310' then 1 end) as " CC checkin",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'u' then 1 end) as "CC inhouse",
count (case when circ.item_location_code like 'gc%' and circ.op_code = 'f' then 1 end) as "CC Holds",
count (case when circ.stat_group_code_num = '311' and circ.op_code = 'o' then 1 end) as "CC selfcheck",
count (case when circ.op_code = 'o' and circ.pcode3 <> '0' and circ.item_location_code like 'gc%' then 1 end) as "CC C-Car Check-outs",
count (case when circ.op_code = 'o' and (circ.ptype_code = '15' or circ.ptype_code = '22' or circ.ptype_code = '28') and circ.item_location_code like 'gc%' then 1 end) as "CC EAN Check-outs"


from
  sierra_view.circ_trans as circ


where
  transaction_gmt  > now() - interval '30 day' ;


